# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb82a53dcf01403269ed5fdc93590d1aeaf5c4eeb934ac18b9f7cf318996805850719c538ed5fcacda367996a8cc0d005b9369b23a0b003fcc224209ee0fb5d0

test:
  secret_key_base: e549313d4c511a2b410022930c1f7229bb1fafaa2551f7a0a2bdbf22f559a834a73890c84c062acd6c86ab7cdab8a573076e035f3abe7715c37ac6bfbab38fab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
